### ISSUE TITLE
Allow newer Terraform versions

### ISSUE THREAD

**Issue by andrewmackett** [memes/terraform-google-secret-manager#7]
## Allow use of Terraform versions newer than 0.13

This module currently sets `required_version = "~> 0.13"` which limits it's use to Terraform 0.13 _only_.
I assume this is because the module was only tested with Terraform 0.13, as you mention in the [README](https://github.com/memes/terraform-google-secret-manager/blob/main/README.md).

Terraform's [version constraints](https://www.terraform.io/docs/language/expressions/version-constraints.html#terraform-core-and-provider-versions) docs say:
> Reusable modules should constrain only their minimum allowed versions of Terraform and providers

Could this module set `required_version = ">= 0.13"` to allow newer versions of Terraform to be used?

## Are you willing to contribute?

Yes! I've opened pull request https://github.com/memes/terraform-google-secret-manager/pull/6

**Comment by memes** [comment]
Thank you for raising the issue and submitting PR #6. Marking this issue as closed
